defaults: &defaults
  default_login: "admin"
  default_password: "admin"
  jwt_secret_key: "secret"
  google_places_api_key: "<%= ENV['GOOGLE_MAPS_API_KEY'] %>"

development:
  <<: *defaults

test:
  <<: *defaults

audit_test:
  <<: *defaults

audit_development:
  <<: *defaults

audit_production:
  <<: *defaults

production:
 <<: *defaults

