defaults: &defaults
  default_login: "admin"
  default_password: "DGZ*{l<jc=iVSjR"
  jwt_secret_key: "secret"
  google_places_api_key: "AIzaSyAGdk98z1IBEapX_nyDiqxJQQ96ttcTVrY"

development:
  <<: *defaults

test:
  <<: *defaults

audit_test:
  <<: *defaults

audit_development:
  <<: *defaults

audit_production:
  <<: *defaults

production:
 <<: *defaults

